In [ ]:
import numpy as np

In [ ]:
Advanced array creation with specific dtypes

In [2]:
import numpy as np
complex_array = np.array([1+2j, 3+4j], dtype=np.complex128)
print("Complex array:", complex_array)

Complex array: [1.+2.j 3.+4.j]


In [ ]:
Memory layout optimization (order parameter)

In [3]:
import numpy as np
c_order_array = np.array([[1, 2, 3], [4, 5, 6]], order='C')
f_order_array = np.array([[1, 2, 3], [4, 5, 6]], order='F')
print("C-order array:", c_order_array)
print("F-order array:", f_order_array)

C-order array: [[1 2 3]
 [4 5 6]]
F-order array: [[1 2 3]
 [4 5 6]]


In [ ]:
Memory views and broadcasting

In [4]:
import numpy as np
x = np.arange(6).reshape(2, 3)
y = x[:, np.newaxis, :]
print("Memory view and broadcasting array:\n", y)

Memory view and broadcasting array:
 [[[0 1 2]]

 [[3 4 5]]]


In [ ]:
Manipulating the shape and size of arrays

In [5]:
flattened = x.flatten()
print("Flattened array:", flattened)

Flattened array: [0 1 2 3 4 5]


In [6]:
raveled = x.ravel()
print("Raveled array:", raveled)

Raveled array: [0 1 2 3 4 5]


In [ ]:
Tile and repeat arrays

In [7]:
tiled = np.tile(x, (2, 1))
print("Tiled array:\n", tiled)

Tiled array:
 [[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


In [8]:
repeated = np.repeat(x, 2, axis=0)
print("Repeated array:\n", repeated)

Repeated array:
 [[0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]]


In [ ]:
Masked arrays

In [9]:
masked_array = np.ma.array(x, mask=x > 2)
print("Masked array:\n", masked_array)

Masked array:
 [[0 1 2]
 [-- -- --]]


In [ ]:
Advanced linear algebra operations


Singular Value Decomposition (SVD)

In [10]:
u, s, vh = np.linalg.svd(x, full_matrices=False)
print("U matrix:\n", u)
print("Singular values:", s)
print("V^H matrix:\n", vh)

U matrix:
 [[-0.27472113  0.96152395]
 [-0.96152395 -0.27472113]]
Singular values: [7.34846923 1.        ]
V^H matrix:
 [[-0.39254051 -0.56077215 -0.7290038 ]
 [-0.82416338 -0.13736056  0.54944226]]


In [ ]:
QR Decomposition

In [11]:
q, r = np.linalg.qr(x)
print("Q matrix:\n", q)
print("R matrix:\n", r)

Q matrix:
 [[ 0. -1.]
 [-1.  0.]]
R matrix:
 [[-3. -4. -5.]
 [ 0. -1. -2.]]


In [ ]:
Cholesky Decomposition

In [12]:
A = np.array([[1, 2], [2, 5]])
cholesky_decomp = np.linalg.cholesky(A)
print("Cholesky decomposition:\n", cholesky_decomp)

Cholesky decomposition:
 [[1. 0.]
 [2. 1.]]


In [ ]:
Eigenvalue decomposition

In [13]:
eigenvalues, eigenvectors = np.linalg.eigh(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [0.17157288 5.82842712]
Eigenvectors:
 [[-0.92387953  0.38268343]
 [ 0.38268343  0.92387953]]


In [ ]:
Fourier Transforms

In [14]:
fft_array = np.fft.fft([1, 2, 3, 4])
print("FFT of array:", fft_array)

FFT of array: [10.+0.j -2.+2.j -2.+0.j -2.-2.j]


In [15]:
ifft_array = np.fft.ifft(fft_array)
print("Inverse FFT of array:", ifft_array)

Inverse FFT of array: [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [ ]:
Gradient and numerical differentiation

In [16]:
x = np.linspace(0, 10, 15)
y = np.sin(x)
gradient = np.gradient(y, x)
print("Gradient of y with respect to x:", gradient)

Gradient of y with respect to x: [ 0.91710906  0.69293215  0.12999645 -0.49649157 -0.88025613 -0.83368344
 -0.37954184  0.26014916  0.77265913  0.90743359  0.59858436 -0.00289918
 -0.60296538 -0.90825549 -0.9556918 ]


In [ ]:
Advanced statistical functions

In [17]:
percentile_90 = np.percentile(x, 90)
print("90th percentile:", percentile_90)

quantiles = np.quantile(x, [0.25, 0.5, 0.75])
print("Quantiles (25%, 50%, 75%):", quantiles)

90th percentile: 9.0
Quantiles (25%, 50%, 75%): [2.5 5.  7.5]


In [ ]:
Advanced random number generation

Random samples from a multivariate normal distribution

In [18]:
mean = [0, 0]
cov = [[1, 0.5], [0.5, 1]]
multivar_normal = np.random.multivariate_normal(mean, cov, 1000)
print("Multivariate normal samples:\n", multivar_normal[:5])

Multivariate normal samples:
 [[-1.37950475 -0.3608752 ]
 [ 0.5488923   0.12376359]
 [ 0.45957741  1.34279064]
 [ 0.07766664 -0.72547353]
 [ 0.25018858  1.40772346]]


In [ ]:
Working with large datasets

Memory-mapped files for large datasets

In [19]:
large_array = np.memmap('large_array.dat', dtype='float32', mode='w+', shape=(1000, 1000))
large_array[:] = np.random.random((1000, 1000))
print("Large array using memmap:\n", large_array)

Large array using memmap:
 [[0.5517069  0.625127   0.28824514 ... 0.335688   0.75485647 0.12456546]
 [0.42455345 0.1237372  0.00763588 ... 0.03025853 0.20616902 0.24198219]
 [0.9657104  0.6872292  0.09361833 ... 0.09692259 0.54673225 0.98562753]
 ...
 [0.62150055 0.42994517 0.6301443  ... 0.95290226 0.37349352 0.17596494]
 [0.12116293 0.05929414 0.3259916  ... 0.36909208 0.95684445 0.9793124 ]
 [0.8184563  0.42437795 0.32313332 ... 0.01789521 0.688961   0.48136896]]


In [ ]:
Sliding window view for advanced slicing

In [20]:
from numpy.lib.stride_tricks import sliding_window_view
array = np.arange(10)
window_size = 3
sliding_windows = sliding_window_view(array, window_shape=window_size)
print("Sliding window view:\n", sliding_windows)

Sliding window view:
 [[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
Sparse matrix operations with Scipy integration

In [21]:
from scipy import sparse
a = np.arange(25).reshape(5, 5)
sparse_matrix = sparse.csr_matrix(a)
print("Sparse matrix:\n", sparse_matrix)

Sparse matrix:
   (0, 1)	1
  (0, 2)	2
  (0, 3)	3
  (0, 4)	4
  (1, 0)	5
  (1, 1)	6
  (1, 2)	7
  (1, 3)	8
  (1, 4)	9
  (2, 0)	10
  (2, 1)	11
  (2, 2)	12
  (2, 3)	13
  (2, 4)	14
  (3, 0)	15
  (3, 1)	16
  (3, 2)	17
  (3, 3)	18
  (3, 4)	19
  (4, 0)	20
  (4, 1)	21
  (4, 2)	22
  (4, 3)	23
  (4, 4)	24


In [ ]:
Sparse matrix operations

In [22]:
sparse_matrix_sum = sparse_matrix.sum()
print("Sum of sparse matrix elements:", sparse_matrix_sum)

Sum of sparse matrix elements: 300


In [23]:
# element wise
squared_elements = np.square(a)
print("Squared elements using np.ufunc:\n", squared_elements)

Squared elements using np.ufunc:
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


In [ ]:
Broadcasting with np.newaxis for higher-dimensional operations

In [24]:
array_3d = array[:, np.newaxis]
print("Array expanded to 3D with newaxis:\n", array_3d)

Array expanded to 3D with newaxis:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
Vectorized string operations

In [25]:
string_array = np.array(['hello', 'world', 'numpy'])
uppercased = np.char.upper(string_array)
print("Uppercased string array:", uppercased)

Uppercased string array: ['HELLO' 'WORLD' 'NUMPY']


In [ ]:
Vectorized datetime operations

In [26]:
dates = np.array(['2023-01-01', '2024-01-01'], dtype='datetime64')
date_diffs = dates - np.datetime64('2023-01-01')
print("Date differences in days:", date_diffs)

Date differences in days: [  0 365]
