In [ ]:
!pip install numpy

In [ ]:
# import the library
import numpy as np

In [ ]:
Creating different types of arrays

In [3]:
# Create a NumPy array from a list
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

Array: [1 2 3 4 5]


In [4]:
# Create a 2D array (matrix) from a list of lists
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

Matrix:
 [[1 2 3]
 [4 5 6]]


In [5]:
# Create an array of zeros
import numpy as np
zeros = np.zeros((3, 3))
print("Zeros:\n", zeros)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Create an array of ones
import numpy as np
ones = np.ones((2, 4))
print("Ones:\n", ones)

Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# Create an array with a specified range
# start, stop, step
import numpy as np
range_array = np.arange(0, 10, 2)  
print("Range array:", range_array)

Range array: [0 2 4 6 8]


In [8]:
# Create an array of evenly spaced values
# start, stop, number of points
import numpy as np
linspace_array = np.linspace(0, 1, 5)  
print("Linspace array:", linspace_array)

Linspace array: [0.   0.25 0.5  0.75 1.  ]


In [9]:

# Reshape an array
import numpy as np
reshaped = np.arange(12).reshape(3, 4)
print("Reshaped array:\n", reshaped)



Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
Basic operations

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Addition
add = a + b
print("Addition:", add)

Addition: [5 7 9]


In [12]:
# Subtraction
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sub = a - b
print("Subtraction:", sub)

Subtraction: [-3 -3 -3]


In [13]:
# Element-wise multiplication
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
mul = a * b
print("Element-wise multiplication:", mul)

Element-wise multiplication: [ 4 10 18]


In [14]:
# Element-wise division
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
div = a / b
print("Element-wise division:", div)

Element-wise division: [0.25 0.4  0.5 ]


In [15]:
# Dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Dot product:", dot_product)

Dot product: 32


In [16]:
# Sum of all elements in an array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum_all = np.sum(a)
print("Sum of all elements:", sum_all)

Sum of all elements: 6


In [17]:
# Sum along an axis - sum of each column
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum_axis = np.sum(matrix, axis=0)  
print("Sum along axis 0 (columns):", sum_axis)


Sum along axis 0 (columns): [5 7 9]


In [18]:
# Mean of all elements
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
mean_all = np.mean(a)
print("Mean of all elements:", mean_all)

Mean of all elements: 2.0


In [19]:
# Mean along an axis - mean of each row
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
mean_axis = np.mean(matrix, axis=1)  
print("Mean along axis 1 (rows):", mean_axis)

Mean along axis 1 (rows): [2. 5.]


In [20]:
# Standard deviation
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
std_dev = np.std(a)
print("Standard deviation:", std_dev)

Standard deviation: 0.816496580927726


In [21]:
# Transpose of a matrix
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
transpose_matrix = matrix.T
print("Transpose of matrix:\n", transpose_matrix)

Transpose of matrix:
 [[1 4]
 [2 5]
 [3 6]]


In [22]:
# Indexing and slicing
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sliced_array = arr[1:4]  # slice from index 1 to 3
print("Sliced array:", sliced_array)

Sliced array: [2 3 4]


In [23]:
# Boolean indexing
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
bool_index = arr > 3
print("Boolean indexing (arr > 3):", bool_index)
filtered_array = arr[bool_index]
print("Filtered array:", filtered_array)

Boolean indexing (arr > 3): [False False False  True  True]
Filtered array: [4 5]


In [24]:
# Concatenate arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concat = np.concatenate((a, b))
print("Concatenated array:", concat)

Concatenated array: [1 2 3 4 5 6]


In [ ]:
Other operations

In [25]:
# Stack arrays vertically
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vstack = np.vstack((a, b))
print("Vertically stacked array:\n", vstack)

Vertically stacked array:
 [[1 2 3]
 [4 5 6]]


In [26]:
# Stack arrays horizontally
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
hstack = np.hstack((a, b))
print("Horizontally stacked array:", hstack)

Horizontally stacked array: [1 2 3 4 5 6]


In [27]:
# Create identity matrix
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
identity_matrix = np.eye(3)
print("Identity matrix:\n", identity_matrix)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# Random numbers
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
random_array = np.random.random((3, 3))  # random values in a given shape
print("Random array:\n", random_array)

Random array:
 [[0.50584571 0.9190762  0.24226044]
 [0.99884389 0.89685366 0.94006391]
 [0.28722126 0.20645713 0.4303812 ]]


In [29]:
# Seed for reproducibility
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.random.seed(42)
random_seeded = np.random.random((2, 2))
print("Random array with seed:\n", random_seeded)

Random array with seed:
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
