In [ ]:
# import library
import numpy as np

In [ ]:
Creating arrays with random values from a normal distribution

In [1]:
# mean=0, std=1
import numpy as np
normal_dist = np.random.normal(loc=0, scale=1, size=(3, 3)) 
print("Normal distribution array:\n", normal_dist)

Normal distribution array:
 [[-0.27205711  1.80847591  1.02508128]
 [ 1.12162684 -1.18998229 -0.2232259 ]
 [ 1.07022859  0.40661123  0.00589061]]


In [ ]:
Generating random integers

In [3]:
# low, high, size
import numpy as np
rand_ints = np.random.randint(0, 10, size=(3, 3))  
print("Random integers array:\n", rand_ints)

Random integers array:
 [[7 7 1]
 [0 3 0]
 [9 4 4]]


In [ ]:
Creating an array with random values from a uniform distribution

In [4]:
# low, high, size
import numpy as np
uniform_dist = np.random.uniform(low=0, high=1, size=(3, 3)) 
print("Uniform distribution array:\n", uniform_dist)

Uniform distribution array:
 [[0.5680915  0.88071404 0.37117314]
 [0.58701693 0.92395974 0.15088461]
 [0.49809421 0.17041021 0.01969703]]


In [ ]:
Advanced indexing with integer arrays

In [5]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
index_array = np.array([0, 2, 4])
indexed_array = a[index_array]
print("Indexed array:", indexed_array)

Indexed array: [10 30 50]


In [ ]:
Advanced indexing with boolean arrays

In [6]:
import numpy as np
b = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (b > 2)
print("Boolean indexing (b > 2):\n", bool_idx)
filtered_b = b[bool_idx]
print("Filtered array:", filtered_b)

Boolean indexing (b > 2):
 [[False False]
 [ True  True]
 [ True  True]]
Filtered array: [3 4 5 6]


In [ ]:
Broadcasting

In [7]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([1, 0, 1])
broadcasted_sum = x + y
print("Broadcasted sum:\n", broadcasted_sum)

Broadcasted sum:
 [[2 2 4]
 [5 5 7]]


In [ ]:
Stacking arrays depth-wise

In [9]:
depth_stack = np.dstack((x, x))
print("Depth-wise stacked array:\n", depth_stack)

Depth-wise stacked array:
 [[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


In [ ]:
Splitting arrays

In [10]:
# split into 2 sub-arrays
split_array = np.split(x, 2)  
print("Split array:", split_array)

Split array: [array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
Finding unique elements

In [11]:
c = np.array([1, 2, 2, 3, 3, 3])
unique_elements = np.unique(c)
print("Unique elements:", unique_elements)

Unique elements: [1 2 3]


In [ ]:
Finding unique elements and their counts

In [12]:
unique_elements, counts = np.unique(c, return_counts=True)
print("Unique elements with counts:", unique_elements, counts)

Unique elements with counts: [1 2 3] [1 2 3]


In [ ]:
Linear algebra operations

In [ ]:
matrix = np.array([[1, 2], [3, 4]])

In [ ]:
Inverse of a matrix

In [13]:
inverse_matrix = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse_matrix)

NameError: name 'matrix' is not defined

In [ ]:
Determinant of a matrix

In [14]:
det_matrix = np.linalg.det(matrix)
print("Determinant of matrix:", det_matrix)

NameError: name 'matrix' is not defined

In [ ]:
Eigen values and Eigen vectors

In [15]:
eigen = np.linalg.eig(matrix)
# this returns two values
print(eigen)

NameError: name 'matrix' is not defined

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

In [ ]:
Solving linear equations

In [ ]:
Solve Ax=b

In [16]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
solution = np.linalg.solve(A, b)
print("Solution of linear equations:", solution)

Solution of linear equations: [2. 3.]


In [ ]:
Matrix multiplication

In [17]:
matrix_mul = np.matmul(A, matrix)
print("Matrix multiplication:\n", matrix_mul)

NameError: name 'matrix' is not defined

In [ ]:
Element-wise power

In [18]:
powered_array = np.power(A, 2)
print("Element-wise power:", powered_array)

Element-wise power: [[9 1]
 [1 4]]


In [ ]:
Applying a function element-wise

In [19]:
def custom_func(x):
    return x ** 2 + 1

applied_func = np.vectorize(custom_func)(A)
print("Applied custom function:", applied_func)

Applied custom function: [[10  2]
 [ 2  5]]


In [ ]:
Logical operators

In [20]:
logical_and = np.logical_and(a > 10, a < 50)
print("Logical AND:", logical_and)

Logical AND: [False  True  True  True False]


In [21]:
logical_or = np.logical_or(a < 10, a > 30)
print("Logical OR:", logical_or)

Logical OR: [False False False  True  True]


In [ ]:
Saving and loading arrays

In [22]:
np.save('saved_array.npy', a)
loaded_array = np.load('saved_array.npy')
print("Loaded array from file:", loaded_array)

Loaded array from file: [10 20 30 40 50]


In [ ]:
Saving and loading text files

In [23]:
np.savetxt('saved_array.txt', a, delimiter=',')
loaded_text_array = np.loadtxt('saved_array.txt', delimiter=',')
print("Loaded array from text file:", loaded_text_array)

Loaded array from text file: [10. 20. 30. 40. 50.]


In [ ]:
Generating meshgrid for 3D plots or functions

In [24]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)

X, Y = np.meshgrid(x, y)
Z = np.sin(X) + np.cos(Y)

print("Meshgrid X:\n", X)
print("Meshgrid Y:\n", Y)
print("Computed Z:\n", Z)

Meshgrid X:
 [[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889  5.        ]
 [-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
   1.66666667  2.77777778  3.88888889 

In [ ]:
Applying condition to elements

In [25]:
cond_array = np.where(a > 20, a, -1)
print("Conditionally modified array:", cond_array)

Conditionally modified array: [-1 -1 30 40 50]


In [ ]:
Working with structured arrays

In [26]:
structured_array = np.array([(1, 'A'), (2, 'B'), (3, 'C')],
                            dtype=[('number', 'i4'), ('letter', 'U1')])
print("Structured array:", structured_array)
print("Structured array field 'number':", structured_array['number'])
print("Structured array field 'letter':", structured_array['letter'])

Structured array: [(1, 'A') (2, 'B') (3, 'C')]
Structured array field 'number': [1 2 3]
Structured array field 'letter': ['A' 'B' 'C']
